#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-disruptor
Version  : 3.3.0
Release  : 1
URL      : https://github.com/LMAX-Exchange/disruptor/archive/3.3.0.tar.gz
Source0  : https://github.com/LMAX-Exchange/disruptor/archive/3.3.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/lmax/disruptor/3.3.0/disruptor-3.3.0.jar
Source2  : https://repo1.maven.org/maven2/com/lmax/disruptor/3.3.0/disruptor-3.3.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-disruptor-data = %{version}-%{release}

%description
## LMAX Disruptor
A High Performance Inter-Thread Messaging Library
## Maintainer

%package data
Summary: data components for the mvn-disruptor package.
Group: Data

%description data
data components for the mvn-disruptor package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/lmax/disruptor/3.3.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/lmax/disruptor/3.3.0/disruptor-3.3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/lmax/disruptor/3.3.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/lmax/disruptor/3.3.0/disruptor-3.3.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/lmax/disruptor/3.3.0/disruptor-3.3.0.jar
/usr/share/java/.m2/repository/com/lmax/disruptor/3.3.0/disruptor-3.3.0.pom
